# Generated by Django 5.2.7 on 2025-11-05 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mService', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsonfile',
            name='client_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
