# Generated by Django 5.2.7 on 2025-11-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mService', '0003_project_delete_jsonfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
