# Generated by Django 5.2.7 on 2025-11-24 17:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mService', '0006_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='Only English letters and numbers allowed.', max_length=200, null=True, validators=[django.core.validators.RegexValidator(message='Project name may contain only English letters (A-Z, a-z) and numbers (0-9).', regex='^[A-Za-z0-9]+$')]),
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default='untitled project', help_text='Only English letters and numbers allowed.', max_length=20, validators=[django.core.validators.RegexValidator(message='Project name may contain only English letters (A-Z, a-z) and numbers (0-9).', regex='^[A-Za-z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='client_id',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='schema',
            name='name',
            field=models.CharField(default='untitled schema', help_text='Only English letters and numbers allowed.', max_length=20, validators=[django.core.validators.RegexValidator(message='Project name may contain only English letters (A-Z, a-z) and numbers (0-9).', regex='^[A-Za-z0-9]+$')]),
        ),
    ]
