# Generated by Django 5.2.7 on 2025-12-03 22:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mService', '0007_project_description_project_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='Only English letters and numbers allowed.', max_length=200, null=True, validators=[django.core.validators.RegexValidator(message='Project name may contain only English letters (A-Z, a-z) and numbers (0-9).', regex='^[A-Za-z0-9]+(?: [A-Za-z0-9]+)*$')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default='untitled project', help_text='Only English letters and numbers allowed.', max_length=20, validators=[django.core.validators.RegexValidator(message='Project name may contain only English letters (A-Z, a-z) and numbers (0-9).', regex='^[A-Za-z0-9]+(?: [A-Za-z0-9]+)*$')]),
        ),
        migrations.AlterField(
            model_name='schema',
            name='name',
            field=models.CharField(default='untitled schema', help_text='Only English letters and numbers allowed.', max_length=20, validators=[django.core.validators.RegexValidator(message='Project name may contain only English letters (A-Z, a-z) and numbers (0-9).', regex='^[A-Za-z0-9]+(?: [A-Za-z0-9]+)*$')]),
        ),
    ]
